#USER SETTINGS
set-option -sg escape-time 200
# set-option -g default-terminal "screen-256color"
set-option -g mouse on

set-option -g status-right '%H:%M'

set-option -g set-clipboard on
  


set-option -ga terminal-overrides ",xterm-256color:Tc"

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# alt up/down pane horizontal pane switching
# bind -n M-Up select-pane -U \; if-shell -F "#{window_zoomed_flag}" "resize-pane -Z"
bind -n M-Up 'select-pane -U'
# bind -n M-Down select-pane -D \; if-shell -F "#{window_zoomed_flag}" "resize-pane -Z"
bind -n M-Down 'select-pane -D ; resize-pane -Z'

bind -n M-Left previous-window
bind -n M-Right next-window

# Move window left with Shift+Option+Left
bind -n S-M-Left swap-window -t -1\; select-window -t -1

# Move window right with Shift+Option+Right
bind -n S-M-Right swap-window -t +1\; select-window -t +1

# make tmux clear scrollback buffer by pressing ctrl+k (without prefix)
bind -n C-k clear-history

# prevent sticky keys when switching panes
set -g repeat-time 50

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
run '~/.tmux/plugins/tpm/tpm'
